# Generated by Django 3.0 on 2020-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastryHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=True),
        ),
    ]
