# Generated by Django 3.0 on 2020-01-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('Update_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_id', models.IntegerField(default='')),
                ('Update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
